spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: c##chakir
    password: chakir2001
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        cache:
          use_second_level_cache: false
          use_query_cache: false

logging:
  level:
    org.springframework.security: DEBUG