version: '3.8'
services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=chakir2001
      - APP_USER=c##chakir
      - APP_USER_PASSWORD=chakir2001
    ports:
      - "1521:1521"
    volumes:
      - ../backend/src/main/resources/ticket_management_schema.sql:/docker-entrypoint-initdb.d/ticket_management_schema.sql
    networks:
      - app-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: it-support-backend
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=c##chakir
      - SPRING_DATASOURCE_PASSWORD=chakir2001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge